#!/usr/bin/python
#coding=utf8
import os, sys
import paramiko
import threading as thr
import coloration as col
import logger

class ModuleDeployer(thr.Thread):
    ''' thread to deploy a module'''
    lgr = None
    ssh = None
    sftp = None
    config = None
    package_filename = ''

    def __init__(self, module_config):
        thr.Thread.__init__(self)
        self.lgr = logger.Logger(module_config.module_name)
        self.config = module_config

        # init ssh tools
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(module_config.hostname, int(module_config.port), module_config.username, module_config.password)
        sftp = ssh.open_sftp()

    def sshExec(cmd):
        lgr.log(col.green('==> ') + col.yellow(cmd))
        return client.exec_command(cmd)

    def sshCmd(cmd, ignoreError = False):
        stdin, stdout, stderr = sshExec(cmd)
        line = stdout.readline()
        while len(line) > 0:
            print line,
            lgr.log(line)
            line = stdout.readline()
        errInfo = stderr.read()
        if len(errInfo) > 0:
            lgr.log(col.red('execute cmd failed => ' + errInfo))
            if not ignoreError:
                sys.exit(1)

    def upload(self):
        target_path = '/tmp/%s' % (self.package_filename)
        lgr.log(col.yellow('transfer package(%s), from %s to %s' % (self.package_filename, config.package_path, target_path)));
        sftp.put(config.package_path, target_path)

    def stop_tomcat(self):
        stdin, stdout, stderr = sshExec("ps aux|grep %s/bin|grep -v 'grep'|awk '{print $2}'" % (config.tomcat_dir))
        pidlist = stdout.read()
        for pid in pidlist:
            sshCmd("kill -9 " + pid)

    def replace_package(self):
        placeholders = { 'tomcat_dir' : config.tomcat_dir, 'package_filename' : self.package_filename, 'backup_dir' : config.backup_dir }
        placeholders["timestamp"] = datetime.now().strftime("%Y%m%d_%H%M%S")
        sshCmd('test -f %(tomcat_dir)s/webapps/%(package_filename)s && mv %(tomcat_dir)s/webapps/%(package_filename)s %(backup_dir)s/%(package_filename)s_%(timestamp)s' % placeholders, True)
        sshCmd('rm -rf %(tomcat_dir)s/webapps/%(package_filename)s*' % placeholders)
        sshCmd('rm -rf %(tomcat_dir)s/work/*' % placeholders)
        sshCmd('mv /tmp/%(package_filename)s.war %(tomcat_dir)s/webapps/%(package_filename)s.war' % placeholders)

    def start_tomcat(self):
        sshCmd('%(tomcat_di)s/bin/startup.sh' % dict)

    def run(self):
        if not os.path.exists(self.config.package_path):
            lgr.log(col.red('package not found, fail this deployment.'))
            return 'failed'
        self.package_filename = os.path.basename(self.config.package_path)
        self.upload()
        self.stop_tomcat()
        self.replace_package()
        self.start_tomcat()

class ModuleConfig:
    module_name = ''
    hostname = ''
    port = 0
    username = ''
    password = ''
    tomcat_dir = ''
    package_path = ''
    backup_dir = ''
    config_dict = None

    def __init__(self, values):
        self.module_name = values["module-name"]
        self.hostname = values["hostname"]
        self.port = values["port"]
        self.username = values["username"]
        self.password = values["password"]
        self.tomcat_dir = values["tomcat-dir"]
        self.package_path = values["package-path"]
        self.backup_dir = values["backup-dir"]


